Check type of $cvsviewertype before converting to lowercase
This commit fixes the following error.

production.ERROR: strtolower():
Argument #1 ($string) must be of type string, null given
/cdash/app/Utils/RepositoryUtils.php:31